/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teambootje;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author kevin
 */
public class A10 extends javax.swing.JFrame {

    /**
     * Creates new form A10
     */
    public A10() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Create and set up the window.
        setTitle("SS Rotterdam Analyse || Readme");
        ImageIcon icon = new ImageIcon("img/bootje.jpg");
        setLocationRelativeTo(null);
        setIconImage(icon.getImage());
        setLayout(new BorderLayout());
        setSize(700,750);
        setResizable(false);
        
        JButton back = new JButton("Back");
        add(back, BorderLayout.NORTH);
        
        
        JPanel readme = new JPanel();
        JScrollPane scroll = new JScrollPane(readme);
        scroll.setPreferredSize(new Dimension(400, 400));
        add(scroll, BorderLayout.CENTER);
        JLabel read = new JLabel(
                "<html>"
                        + "<h1 style=\"text-align: center\">Readme</h1>"
                        + "Dit programma is Speciaal gemaak voor analyse voor het gebouw/schip De SSRotterdam.<br>"
                        + "<br>"
                        + "Get Twitter / Facebook Data:<br>"
                        + "De 'Get Twitter / Facebook Data' optie doet eigenlijk wat het zegt, het haalt posts van Twitter & Facebook binnen.<br>"
                        + "Behalve de posts worden ook de persoons informatie binnen gehaald.<br>"
                        + "Alle binnengehaalde informatie wordt vervolgens achter elkaar geplaatst en getoond en in de database geplaats.<br>"
                        + "<br>"
                        + "De centrale knoppen voeren allemaal een analyse over de bestaande data uit.<br>"
                        + "Wanneer u op de knop drukt wordt de analyse uitgevoerd en wordt er een overzicht van de data zichtbaar.<br>"
                        + "Vervolgens heeft u 2 opties, Back of Chart.<br>"
                        + "Met de Back knop gaat u terug naar het hoofdmenu.<br>"
                        + "Als u op Chart klikt wordt de data in een grafiek gezet voor een visueel duidelijker overzicht.<br>"
                        + "Het overzicht met de grafiek kunt u vervolgens sluiten door op het kruisje te klikken.<br>"
                        + "<br>"
                        + "Geslacht bezoeker:<br>"
                        + "Laat zien hoeveel van de mensen man of vrouw zijn.<br>"
                        + "Welk seizoen:<br>"
                        + "Geeft een overzicht van op welke datum het meest / minst wordt gepost.<br>"
                        + "Posts per locatie:<br>"
                        + "Uit welke stad komen de meeste / minste posts.<br>"
                        + "Positieve posts:<br>"
                        + "-<br>"
                        + "Leeftijd bezoekers:<br>"
                        + "Overzicht van hoe oud de bezoekers zijn.<br>"
                        + "Waar bezoeker vandaan komt:<br>"
                        + "Laat niet zien hoeveel posts er per locatie zijn, maar waar de personen in de database vandaan komen.<br>"
                        + "Doelgroep:<br>"
                        + "Hoeveel mensen behoren tot een bepaalde doelgroep.<br>"
                        + "Posts per doelgroep:<br>"
                        + "Laat alle posts zien gesorteerd op doelgroep.<br>"
                        + "Meeste berichten:<br>"
                        + "Laat zien hoeveel posts een persoon geplaatst heeft.<br>"
                        + "<br>"
                        + "Vervolgens is er de Bekijk Data knop.<br>"
                        + "Dit brengt u naar een overzicht waar alle posts staan en wanneer deze zijn geplaatst.<br>"
                        + "<br>"
                        + "Gemaakt door:<br> Johan Bos,<br> Kevin Verweij,<br> Roy van den Heuvel, <br> Steven van der Stel"
             + "</html>"
        );
        readme.add(read);
        
        back.addActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
